version: '3.8'

services:
  # The Django Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cerno_backend
    command: >
      sh -c "python manage.py migrate &&
            uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - ./agent_outputs:/app/agent_outputs
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cerno_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
